### ISSUE TITLE
Edit KSU name for Marietta Campus in Open Trip Planner

### ISSUE THREAD

**Issue by AaronWFowler** [atlregional/atltransit.org#100]
Kennesaw State University merged with SPSU last year. SPSU is still listed on the map. KSU - Marietta Campus should be listed in its place.

**Comment by AaronWFowler** [comment]
This appears updated in OpenStreetMap, not sure why the name Kennesaw State University Marietta Campus is not coming up in the ATLtransit destination field.

**Comment by AaronWFowler** [comment]
@landonreed I'm going to re-assign this to you to look at.  See notes up above; I'm just unsure why the drop down list of potential addressing isn't picking up the kennesaw state university marietta campus.

**Comment by landonreed** [comment]
Hey @AaronWFowler, so atltransit is no longer using the OpenStreetMap geocoder.  We switched to the esri one because the OSM one wasn't cutting it.  So, that's why you're not seeing it updated in the map/search.  As far as I know, there's no way to fix/update esri's results.

**Comment by AaronWFowler** [comment]
@landonreed you think this might be the right form?  
http://support.esri.com/cn/knowledgebase/techarticles/detail/41401

Does the ESRI map we're using have a specific name?

**Comment by landonreed** [comment]
Hmm, I"m not sure.  This seems more like issues specific to the map, not the geocoder.  Maybe we should tweet the question at them?
