### ISSUE TITLE
Issues wtih CCT bus route numbering

### ISSUE THREAD

**Issue by AaronWFowler** [atlregional/atltransit.org#101]
Email from user:
I commute via CCT 10C (Express Bus) and I don't think this option is very clear for interested commuters. Specifically, when I plug-in data from my home commute, the 101 bus pops-up as an option. I believe that is the same as 10C, but CCT uses the term 10C and the bus is listed as 10C. If I were a newbie, I could run the risk of waiting around for 101 for a long time. Also, I don't think the ATLTransit routes makes it clear that riders on 10C would need to get to the Marietta Transfer Center (it doesn't drop off directly in front of KSU-Marietta).

**Comment by landonreed** [comment]
@AaronWFowler, looking at the cct routes, I'm actually kind of confused by this.  I thought at first that I had maybe missed one of the routes that was named incorrectly in the GTFS, but this seems to be more related to how the routes are being named by CCT?

Thoughts?

**Comment by AaronWFowler** [comment]
@LandonReed gotcha! It may just require having a heart to heart with Cobb about it. I can reach out to them. Can you give me a little more detail on what exactly they would need to fix?  Is it just the route name in their GTFS they need to fix?  Thanks bud!

On Mar 25, 2016, at 10:03 AM, Landon Reed <notifications@github.com<mailto:notifications@github.com>> wrote:

@AaronWFowlerhttps://github.com/AaronWFowler, looking at the cct routes, I'm actually kind of confused by this. I thought at first that I had maybe missed one of the routes that was named incorrectly in the GTFS, but this seems to be more related to how the routes are being named by CCT?

Thoughts?

##
