### ISSUE TITLE
Investigate communications solution

### ISSUE THREAD

**Issue by landonreed** [atlregional/atltransit.org#14]
social/email/sms alerts/news

**Comment by landonreed** [comment]
@AaronWFowler let me know when you've got the new MailChimp set up.

**Comment by landonreed** [comment]
@AaronWFowler, I'm assigning to you.  Assign back to me when it's set up

**Comment by landonreed** [comment]
@AaronWFowler, just wanted to check in on this one.  I can investigate just transferring my account to you/ARC if that's easier.

**Comment by AaronWFowler** [comment]
@landonreed I decided to hold off on publicly advertising this alerts feature until we discuss more internally when and how we might role this out.  I've just hidden the script with comment tags for now.

**Comment by landonreed** [comment]
@AaronWFowler There's actually another mention of the alerts in the grey "status updates" bar on the home page.  I'll modify that a bit.  

Also, do you mind if I add back in the service alerts mention on the alerts page, but just disable the form and have it say "Coming soon" or something?

Oh and I unbolded the heading "Twitter Alerts."  Headings should not also be marked as bold.

![image](https://cloud.githubusercontent.com/assets/2370911/13605843/8d3d23e2-e517-11e5-9c88-a7fd4f818da2.png)
