### ISSUE TITLE
Replace placeholder/external images with stock or original content

### ISSUE THREAD

**Issue by landonreed** [atlregional/atltransit.org#15]

**Comment by AaronWFowler** [comment]
Landon will send Aaron photos that Barry gave him.  Aaron will replace images.

**Comment by landonreed** [comment]
@AaronWFowler can we close this one out?

**Comment by AaronWFowler** [comment]
Yes all done

Sent from my iPhone

On Mar 4, 2016, at 4:40 PM, Landon Reed <notifications@github.com<mailto:notifications@github.com>> wrote:

@AaronWFowlerhttps://github.com/AaronWFowler can we close this one out?

##
