### ISSUE TITLE
Add support for multilingual

### ISSUE THREAD

**Issue by landonreed** [atlregional/atltransit.org#2]
https://www.sylvaindurand.org/making-jekyll-multilingual/

https://github.com/Phlow/feeling-responsive/blob/gh-pages/_data/language_de.yml

https://github.com/Phlow/feeling-responsive/blob/bef7c30261a00106a225fc88e946aaf44d63c3ac/_layouts/default.html#L5

**Comment by landonreed** [comment]
The language selector in the top right navbar is a stopgap measure.  We may need to go in and identify key labels that need to be properly translated.

**Comment by AaronWFowler** [comment]
@landonreed I'm going to close this one and open translation specific issues that come up.

**Comment by landonreed** [comment]
sounds good @AaronWFowler
