### ISSUE TITLE
Drive + Transit Option

### ISSUE THREAD

**Issue by landonreed** [atlregional/atltransit.org#24]

**Comment by landonreed** [comment]
@AaronWFowler I've talked with @demory about otp's drive to transit option and it sounds like this one may not be possible by launch date.  There are still some issues with otp routing to park and rides.  There are also some server setup issues on ARC IT's side that make this tricky (I'll elaborate in email form).

**Comment by AaronWFowler** [comment]
That's ok!  I thought this seemed like a nice to have

Sent from my iPhone

On Mar 4, 2016, at 7:31 PM, Landon Reed <notifications@github.com<mailto:notifications@github.com>> wrote:

@AaronWFowlerhttps://github.com/AaronWFowler I've talked with @demoryhttps://github.com/demory about otp's drive to transit option and it sounds like this one may not be possible by launch date. There are still some issues with otp routing to park and rides. There are also some server setup issues on ARC IT's side that make this tricky (I'll elaborate in email form).

##

**Comment by landonreed** [comment]
@AaronWFowler, oh actually my past self helped us out!  
1. Go to the test instance.  
2. Click 'Plan' in the nav bar
3. First choose mode car.
4. It asks you to choose a park and ride.
5. Choose park and ride and click "Plan trip from here"
6. Enter destination.
7. Voila

Bit of a workaround, but I say it's good enough for now.
