### ISSUE TITLE
Issues with GRTA

### ISSUE THREAD

**Issue by landonreed** [atlregional/atltransit.org#40]
The fare prices are wrong, our contact info address is wrong, and the system map doesn’t link to anything.  I also saw that at least one of our Park-and-Ride lots has an incorrect map (Newnan).

**Comment by AaronWFowler** [comment]
Landon - I believe I've corrected their address, and updated the system map url.  I don't see where the park and ride lot maps are incorrect and I don't see any incorrect fares.

**Comment by AaronWFowler** [comment]
Also I fixed

**Comment by landonreed** [comment]
Nice work @AaronWFowler!  All of the changes look good to me.  I think the comment about incorrect fares was that I was leaving off the base fare price on grta's agency page.  I've fixed that (http://test.atlb.us/about/agencies/grta/#fares), so I think we check that off the list.

As for park and ride maps, getting an accurate updated copy of that data together has been a nightmare.  Nobody really seems to have a good master copy of data.  So, I think we need to ask for specific errors in the data and go from there.

**Comment by AaronWFowler** [comment]
Oh I did notice that, but just noticed that they were correct.  Thanks for adding the base fare on those.  I will likely spend the bulk of this week looking into what else I can update on the site myself.  If there’s anything else I can help you with please let me know.
