### ISSUE TITLE
Trip Planner states trip plan unsuccessful

### ISSUE THREAD

**Issue by AaronWFowler** [atlregional/atltransit.org#51]
Wasn't able to provide a trip for these addresses:

From: 640 Glen Iris Dr, Atlanta, GA
To: 40 Courtland St, Atlanta, GA

"Your trip plan was unsuccessful. Please modify your trip details and try again."

**Comment by landonreed** [comment]
Is this on the test or production version?

**Comment by AaronWFowler** [comment]
The production site.

**Comment by landonreed** [comment]
Might be an issue with the OTP URL I'm using.  I'll check into this.

swap `otp/plan` for `ws/plan`

**Comment by AaronWFowler** [comment]
@landonreed : here is a screenshot from atltransit.org (live site).  Any address I've plugged in doesn't work.  We should move this to our top priority.
![image](https://cloud.githubusercontent.com/assets/17414486/13471703/acfbc0fe-e07f-11e5-948b-0148e8bec87f.png)

**Comment by AaronWFowler** [comment]
@landonreed It's making it one step further now and going to the trip planner page.  still no route options though. 
![image](https://cloud.githubusercontent.com/assets/17414486/13509045/9d8285bc-e157-11e5-853d-9dfba5e86d84.png)

**Comment by landonreed** [comment]
Until we get the URL paths right on s3, this won't be working.

---

Landon Reed  | http://landonreed.net
@eltiar https://twitter.com/eltiar

**Comment by AaronWFowler** [comment]
Gotcha. Looks like he's still working on it

On Mar 3, 2016, at 4:05 PM, Landon Reed <notifications@github.com<mailto:notifications@github.com>> wrote:

Until we get the URL paths right on s3, this won't be working.

---

Landon Reed | http://landonreed.net
@eltiar https://twitter.com/eltiar

On Thu, Mar 3, 2016 at 3:50 PM, Aaron Fowler <notifications@github.com<mailto:notifications@github.com>>
wrote:

> @landonreed https://github.com/landonreed It's making it one step
> further now and going to the trip planner page. still no route options
> though.
> [image: image]
> https://cloud.githubusercontent.com/assets/17414486/13509045/9d8285bc-e157-11e5-853d-9dfba5e86d84.png
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/atlregional/atltransit.org/issues/51#issuecomment-191956802
> .

##

**Comment by landonreed** [comment]
Closing, this should be fixed once we switch back to ARC server.
