### ISSUE TITLE
Issue w/ legend on "Discounts & Passes" page

### ISSUE THREAD

**Issue by whcwilliamson** [atlregional/atltransit.org#66]
On the “Discounts & passes” page, under “List of all fare passes”, I don’t understand

• = available on Breeze Card
о = can be purchased with Breeze Card stored value

This legend seems to be unnecessary as I cannot find anywhere on the page that shows either a closed or open dot.

http://test.atlb.us/fares/passes/

**Comment by AaronWFowler** [comment]
Removed!  Begone unused legend.
