### ISSUE TITLE
Contact us links

### ISSUE THREAD

**Issue by whcwilliamson** [atlregional/atltransit.org#67]
All the contact us links go nowhere.  I assume this intentional?  If so, do we intend to have a form when we go live?  If not, we should get rid of all the contact us options.

**Comment by AaronWFowler** [comment]
@whcwilliamson Can you show me where you found that link?  The contact us link I'm clicking on is working: http://test.atlb.us/about/contact/

**Comment by whcwilliamson** [comment]
http://test.atlb.us/about/feedback

**Comment by AaronWFowler** [comment]
Fixed.  All broken Contact links found and replaced.
