### ISSUE TITLE
Testing in Internet Explorer

### ISSUE THREAD

**Issue by landonreed** [atlregional/atltransit.org#78]
- [ ] trip planning
- [ ] miscellaneous button clicking
- [ ] real-time widgets
- [ ] ...

**Comment by landonreed** [comment]
@AaronWFowler are you able to do some poking around in IE on the website?  I don't really have a good way of doing this at the moment.

**Comment by lslangley** [comment]
@AaronWFowler + @landonreed - I can do the IE poking right now.

**Comment by lcaceda** [comment]
@landonreed  trip planner map not interactive in IE.
from: https://www.mapbox.com/help/mapbox-browser-support/ "Internet Explorer 9 and below is not supported on Mapbox.com."
the mapbox gallery loads examples but is slow.  

Thoughts? Is it a javascript page loading issue? #

**Comment by lslangley** [comment]
All looks good now.
