### ISSUE TITLE
What's the plan for the airport page?

### ISSUE THREAD

**Issue by lslangley** [atlregional/atltransit.org#82]
@AaronWFowler @landonreed 
http://test.atlb.us/destinations/airport/

**Comment by AaronWFowler** [comment]
@lcaceda @landonreed Actually not sure what these destination pages are, but they're not in any of the navigable drop down menus that I'm aware.

**Comment by AaronWFowler** [comment]
@lcaceda @landonreed oh just noticed that link on the home page.  I'll change that to something else for now.

**Comment by lslangley** [comment]
@AaronWFowler Thanks!

**Comment by AaronWFowler** [comment]
rerouted to a rail map :)
